[package]
name = "rpix"
version = "0.1.3"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
image = { version = "0.25", features = ["default"] }
resvg = "0.46"
usvg = "0.46"
tiny-skia = "0.11"
flate2 = "1.1"
base64 = "0.22"
crossterm = "0.29"
anyhow = "1.0"
atty = "0.2"
pdfium-render = "0.8"
headless_chrome = { version = "1.0", features = ["fetch"] }
directories = "6.0.0"

[dev-dependencies]
rstest = "0.26.1"

[profile.release]
codegen-units = 1
debug = false
lto = "fat"
